### PR TITLE
Initial conversion to sphinx

### PR DESCRIPTION
**Pull request by infinity0**
The main motivation is to support reStructuredText so that we can write more pretty tables.

I've had to tweak various knobs to retain the LaTeX support in markdown, it is still a WIP, but the general structure of the site is working.

### CODE REVIEW

**Comment by infinity0** [comment]
@fgimenez any chance you can have this branch be built in CI so we can see what it looks like? I had to install the following:

~~~~
aptitude install python3-recommonmark
pip3 install -U sphinxcontrib-fulltoc
pip3 install -U sphinx-math-dollar
pip3 install -U sphinx-markdown-tables
~~~~

**Comment by infinity0** [comment]
The extension `sphinx-math-dollar` works well, and works directly on the HTML. However the recommonmark extension is screwing with the LaTeX code inside the markdown as it generates it into HTML, turning stuff like `\( ... \)` into `( .. )` which is then ignored by MathJax. If one manually edits the HTML and converts `( .. )`` back into `\( .. \)` then MathJax works perfectly..

**Comment by infinity0** [comment]
https://github.com/readthedocs/recommonmark/issues/184

**Comment by fgimenez** [comment]
> @fgimenez any chance you can have this branch be built in CI so we can see what it looks like?

@infinity0 sure, take a look at https://github.com/w3f/research/pull/64

**Comment by infinity0** [comment]
Thanks, I will continue with this tomorrow.

Today I did https://github.com/codejamninja/sphinx-markdown-parser/pull/8 which solves readthedocs/recommonmark#184

**Comment by infinity0** [comment]
Until that PR is approved however, CI will need to install my fork: https://github.com/infinity0/sphinx-markdown-parser (and drop sphinx-markdown-tables and recommonmark, which is no longer necessary).

**Comment by fgimenez** [comment]
Nice, https://github.com/codejamninja/sphinx-markdown-parser/pull/8 was already merged and a new sphinx-markdown-parser was published, i've updated #64 to use it and all is working fine :+1:

**Comment by infinity0** [comment]
OK, this now looks mostly like the existing site, except that some of the link-clicking behaviour of the left side TOC is different, which is an inherent difference between how sphinx and mkdocs treats site structure.

The only thing remaining is to recreate the news page.

**Comment by infinity0** [comment]
This is ready to be merged into master, though the last commit ("temporarily use my fork [..]") may be deleted/reverted once https://github.com/bashtage/sphinx-material/pull/10 is merged.

**Pull request merged**
