### PR TITLE
updated xcmp link

### PR DESCRIPTION
**Pull request by jonasW3F**
I was asked by @aaronbarefoot:matrix.parity.io to update a link in the XCMP docs

### CODE REVIEW

**Comment by AlistairStewart** [comment]
Well it doesn't link to the XCMP docs, because there aren't any. It doesn't even link to a good description of XCM.

**Comment by jonasW3F** [comment]
> Well it doesn't link to the XCMP docs, because there aren't any. It doesn't even link to a good description of XCM.
> 
> Maybe https://github.com/paritytech/xcm-format is a good link for XCM.

It's not suppose to the link to some XCMP docs. It should just add a link in the research page of XCMP

**Comment by FlorianFranzen** [comment]
Not sure why the link check does not run anymore. Looks good to me.

**Review by FlorianFranzen — APPROVED** [review]
Not sure why the link check does not run anymore. Looks good to me.

**Comment by AlistairStewart** [comment]
> > Well it doesn't link to the XCMP docs, because there aren't any. It doesn't even link to a good description of XCM.
> > Maybe https://github.com/paritytech/xcm-format is a good link for XCM.
> 
> It's not suppose to the link to some XCMP docs. It should just add a link in the research page of XCMP

Aren't you adding a link to the not very useful https://polkadot.network/cross-chain-communication .

**Comment by hndrx66** [comment]
> > > Well it doesn't link to the XCMP docs, because there aren't any. It doesn't even link to a good description of XCM.
> > > Maybe https://github.com/paritytech/xcm-format is a good link for XCM.
> > 
> > 
> > It's not suppose to the link to some XCMP docs. It should just add a link in the research page of XCMP
> 
> Aren't you adding a link to the not very useful https://polkadot.network/cross-chain-communication .

I requested this as the SEO Manager from the Performance Guild. It's needed more so as the new page for XCM is being outranked in Google as we have so many subdomains outside of the marketing page and polkadot domain. We need a link more so to help Google promote the marketing page, it won't have a negative affect on the users can still navigate back and forth.  The link and it's anchor helps build authority and topical relevance as we are competing with CCIP by example. Happy to provide more if needed but this is the context.

**Pull request merged**
